kind: pipeline
name: default
steps:
#- name: test
#  image: golang:1.14
#  commands:
#    - "go mod download"
#    - "go test -race ./..."
#- name: build
#  image: golang:1.14
#  commands:
#    - "go build cmd/api/main.go"
#- name: dockerhub
#  image: plugins/docker
#  settings:
#    repo: gonzalompp/go-api
#    username:
#      from_secret: dockerhub_username
#    password:
#      from_secret: dockerhub_password
#    tags:
#      - latest
#      - ${DRONE_COMMIT_SHA:0:7}
#      - ${DRONE_COMMIT_BRANCH}
- name: deliver
  image: gonzalompp/drone-kubectl
  settings:
    k8s_server:
      from_secret: k8s_server
    k8s_certificate:
      from_secret: k8s_certificate
    k8s_token:
      from_secret: k8s_token
    k8s_user:
      from_secret: k8s_user
    k8s_prueba: "gonzalo"
  commands:
    - echo "AAA $PLUGIN_K8S_USER"
    - echo "BBB $K8S_USER"
    - echo "CCC $plugin_k8s_user"
    - echo "DDD $k8s_user"
    - echo "EEE $PLUGIN_K8S_PRUEBA"
    - echo "QQQ $K8S_PRUEBA"
    - echo "WWW $plugin_k8s_prueba"
    - echo "EEE $k8s_prueba"