kind: pipeline
name: default
steps:
- name: test
  image: golang:1.14
  commands:
    - "go mod download"
    - "go test -race ./..."
- name: build
  image: golang:1.14
  commands:
    - "go build cmd/api/main.go"